name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore source/Stellar.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution (Release)
        run: msbuild source/Stellar.sln -t:Rebuild -p:Configuration=Release -p:Platform="Any CPU"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Stellar-Release
          path: |
            source/Stellar/bin/Release/
          if-no-files-found: warn
